# Generated by Django 6.0.2 on 2026-04-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('description', models.TextField()),
                ('location', models.CharField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Available')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_registrant', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_signups', to='localevents.event')),
                ('user_registrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'event_type',
                'verbose_name_plural': 'event_types',
                'ordering': ['name'],
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='localevents.eventtype'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'created_on')},
        ),
    ]
