# Generated by Django 6.0.2 on 2026-03-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='localevents.eventtype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
