# Generated by Django 6.0.2 on 2026-04-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_book_available_to_borrow_book_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_to_borrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default='No sypnosis added.'),
        ),
    ]
