# Generated by Django 6.0.2 on 2026-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0005_alter_book_available_to_borrow_alter_book_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
