# Generated by Django 6.0.2 on 2026-04-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Sale', 'On Sale'), ('Out of Stock', 'Out of Stock')], default='Available'),
        ),
    ]
