# Generated by Django 6.0.2 on 2026-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='commissiontype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
