# Generated by Django 6.0.4 on 2026-04-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
        ('commissions', '0005_alter_commission_options_commission_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='commissions.commission'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_job', to='accounts.profile'),
        ),
    ]
