# Generated by Django 6.0.2 on 2026-05-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_commission_options_commission_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='people_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='commissions.commission'),
        ),
        migrations.AlterField(
            model_name='job',
            name='manpower_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='commissions.job'),
        ),
    ]
