# Generated by Django 6.0.2 on 2026-03-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_on'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['name'], 'verbose_name': 'project category', 'verbose_name_plural': 'project categories'},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'created_on')},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='diyprojects.projectcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcategory',
            unique_together={('name', 'description')},
        ),
    ]
