# Generated by Django 6.0.4 on 2026-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0004_alter_project_options_project_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_reviews_imgs'),
        ),
    ]
